[build]
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
    # Removed CSP here (let entry.headers.tsx handle it)

[[redirects]]
  from = "/assets/*"
  to = "/build/client/assets/:splat"
  status = 200

[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/_static/*"
  to = "/_static/:splat"
  status = 200

# 👇 SSR catch-all route (last)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200