[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/build/*"
  to = "/build/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200